### ISSUE TITLE
Just a little problem 

### ISSUE THREAD

**Issue by dutrieux** [bamarc/WicketForge#1]
Hi,

**Thanks for your works to solve the problem with 2021.2**.

I juste have a error with resource bundle  *.xml.properties :

`java.lang.NoClassDefFoundError: com/intellij/lang/properties/PropertiesImplUtil
	at wicketforge.search.PropertiesIndex.getBaseFile(PropertiesIndex.java:99)
	at wicketforge.intention.AddPropertiesIntention.hasResourceFile(AddPropertiesIntention.java:45)
	at wicketforge.intention.AddMarkupIntention.isAvailable(AddMarkupIntention.java:67)
	at wicketforge.intention.AddPropertiesIntention.isAvailable(AddPropertiesIntention.java:29)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:169)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$1(ShowIntentionsPass.java:336)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:202)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:335)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:240)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: com.intellij.lang.properties.PropertiesImplUtil PluginClassLoader(plugin=PluginDescriptor(name=WicketForge, id=WicketForge, descriptorPath=plugin.xml, path=D:\Apps\JetBrains\apps\IDEA-U\ch-1\212.4746.92.plugins\WicketForge, version=6.0.0, package=null), packagePrefix=null, instanceId=30, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 27 more`

![image](https://user-images.githubusercontent.com/1622751/128030873-3d660156-7380-4fe9-8631-53fb297bf26c.png)

I nice feature will be to go to the properties file when I click on key of <wicket:message key=""> :
![image](https://user-images.githubusercontent.com/1622751/128032030-a3905f5f-cd6d-45f0-b4af-58f4ef26acf0.png)

Best regards

Duto

**Comment by bamarc** [comment]
Thank you for the report. Development will continue in the original wicketforge repo.

**Comment by dutrieux** [comment]
You are the boss !
